# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "minizinc" = super.buildPythonPackage rec {
    pname = "minizinc";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/1d/d1dc3d250643defde3d71cd9d64911b057ec38b88bc1555ed55b6260fc4f/minizinc-0.10.0-py3-none-any.whl";
      sha256 = "1qqpxkcxjjgwqns05w0pkb2ppgz64v4vy0dq2116q94bdy353ncb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
